---
title: A Tidyverse Primer
author: David Kane and Pratham Kancherla
tutorial:
  id: a-tidyverse-primer
output:
  learnr::tutorial:
    progressive: yes
    allow_skip: yes
runtime: shiny_prerendered
description: 'Tutorial for Chapter 2: A Tidyverse Primer'
---

```{r setup, include = FALSE}
library(learnr)
library(tutorial.helpers)
knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 
```

```{r copy-code-chunk, child = system.file("child_documents/copy_button.Rmd", package = "tutorial.helpers")}
```

```{r info-section, child = system.file("child_documents/info_section.Rmd", package = "tutorial.helpers")}
```

<!-- CHECKLIST BEFORE STARTING: -->
<!-- * Edit yaml at the top of this file -->
<!-- * Save the file as "tutorial.Rmd" in a new directory under inst/tutorials/. -->
<!-- * Load any necessary libraries for the tutorial in the first code chunk -->
<!-- * Review: https://ppbds.github.io/tutorial.helpers/articles/instructions.html -->
<!-- * Delete this and the other commented instructions below. -->

## Introduction
### 

<!-- Two to four sentence about the main topics covered in this tutorial. Why are we here? What will students get out of giving you 90 minutes of their lives? How does this tutorial connect to other tutorials? -->

## Tidyverse principles
### 

### Exercise 1

Type `mtcars` and hit "Run Code."

```{r tidyverse-principles-1, exercise = TRUE}

```


```{r tidyverse-principles-1-hint-1, eval = FALSE}
mtcars
```

### 

`mtcars` is an R dataframe with information about `r dim(mtcars)[1]` cars. 

### Exercise 2

```{r tidyverse-principles-2, exercise = TRUE}

```

<button onclick = "transfer_code(this)">Copy previous code</button>

```{r tidyverse-principles-2-hint-1, eval = FALSE}

```

### 

### Exercise 3

```{r tidyverse-principles-3, exercise = TRUE}

```

<button onclick = "transfer_code(this)">Copy previous code</button>

```{r tidyverse-principles-3-hint-1, eval = FALSE}

```

### 

### Exercise 4

```{r tidyverse-principles-4}
question_text(NULL,
	answer(NULL, correct = TRUE),
	allow_retry = TRUE,
	try_again_button = "Edit Answer",
	incorrect = NULL,
	rows = 3)
```

### 

### Exercise 5

```{r tidyverse-principles-5, exercise = TRUE}

```

<button onclick = "transfer_code(this)">Copy previous code</button>

```{r tidyverse-principles-5-hint-1, eval = FALSE}

```

### 

## Summary
### 

<!-- Two to four sentences which bring the lessons of the tutorial together for the student. What do they know now that they did not know before? How does this tutorial connect to other tutorials? OK if this is very similar to the Introduction. You made a promise as to what they would learn. You (we hope!) kept that promise.-->

```{r download-answers, child = system.file("child_documents/download_answers.Rmd", package = "tutorial.helpers")}
```
